### ISSUE TITLE
The rendering of BackBee seems broken

### ISSUE THREAD

**Issue by mickaelandrieu** [symfony/symfony-marketing#269]
Hi,

I don't know why but the description of BackBee CMS doe's not appears on the website (http://symfony.com/projects/backbee)

This is the related configuration:

```yaml
name: BackBee
url: http://www.backbee.com/
dependencies: [ Twig, doctrine ]
components:
    - Config
    - Console
    - Debug
    - DependencyInjection
    - EventDispatcher
    - Expression Language
    - Filesystem
    - HttpFoundation
    - HttpKernel
    - Routing
    - Security
    - Serializer
    - Translation
    - Validator
    - Yaml
```
